config/routes.rb
Rails.application.routes.draw do

  resources :ruby_mines
  resources :vs_codes
  # root to: "vs_codes#index"
  root to: "ruby_mines#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ruby_mine.rb
class RubyMine < ApplicationRecord
end

app/models/vs_code.rb
class VsCode < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ruby_mines_controller.rb
class RubyMinesController < ApplicationController
  before_action :set_ruby_mine, only: [:show, :edit, :update, :destroy]

  # GET /ruby_mines
  # GET /ruby_mines.json
  def index
    @ruby_mines = RubyMine.all
  end

  # GET /ruby_mines/1
  # GET /ruby_mines/1.json
  def show
  end

  # GET /ruby_mines/new
  def new
    @ruby_mine = RubyMine.new
  end

  # GET /ruby_mines/1/edit
  def edit
  end

  # POST /ruby_mines
  # POST /ruby_mines.json
  def create
    @ruby_mine = RubyMine.new(ruby_mine_params)

    respond_to do |format|
      if @ruby_mine.save
        format.html { redirect_to @ruby_mine, notice: 'Ruby mine was successfully created.' }
        format.json { render :show, status: :created, location: @ruby_mine }
      else
        format.html { render :new }
        format.json { render json: @ruby_mine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ruby_mines/1
  # PATCH/PUT /ruby_mines/1.json
  def update
    respond_to do |format|
      if @ruby_mine.update(ruby_mine_params)
        format.html { redirect_to @ruby_mine, notice: 'Ruby mine was successfully updated.' }
        format.json { render :show, status: :ok, location: @ruby_mine }
      else
        format.html { render :edit }
        format.json { render json: @ruby_mine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ruby_mines/1
  # DELETE /ruby_mines/1.json
  def destroy
    @ruby_mine.destroy
    respond_to do |format|
      format.html { redirect_to ruby_mines_url, notice: 'Ruby mine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_mine
      @ruby_mine = RubyMine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ruby_mine_params
      params.require(:ruby_mine).permit(:name, :points)
    end
end

app/controllers/vs_codes_controller.rb
# frozen_string_literal: true

class VsCodesController < ApplicationController
  before_action :set_vs_code, only: %i[show edit update destroy]

  # GET /vs_codes
  # GET /vs_codes.json
  def index
    @vs_codes = VsCode.all
  
  end

  # GET /vs_codes/1
  # GET /vs_codes/1.json
  def show; end

  # GET /vs_codes/new
  def new
    @vs_code = VsCode.new
  end

  # GET /vs_codes/1/edit
  def edit; end

  # POST /vs_codes
  # POST /vs_codes.json
  def create
    @vs_code = VsCode.new(vs_code_params)

    respond_to do |format|
      if @vs_code.save
        format.html { redirect_to @vs_code, notice: 'Vs code was successfully created.' }
        format.json { render :show, status: :created, location: @vs_code }
      else
        format.html { render :new }
        format.json { render json: @vs_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vs_codes/1
  # PATCH/PUT /vs_codes/1.json
  def update
    respond_to do |format|
      if @vs_code.update(vs_code_params)
        format.html { redirect_to @vs_code, notice: 'Vs code was successfully updated.' }
        format.json { render :show, status: :ok, location: @vs_code }
      else
        format.html { render :edit }
        format.json { render json: @vs_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vs_codes/1
  # DELETE /vs_codes/1.json
  def destroy
    @vs_code.destroy
    respond_to do |format|
      format.html { redirect_to vs_codes_url, notice: 'Vs code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vs_code
    @vs_code = VsCode.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vs_code_params
    params.require(:vs_code).permit(:name, :points)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ruby_mines_helper.rb
module RubyMinesHelper
end

app/helpers/vs_codes_helper.rb
module VsCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ruby_mines/_form.html.erb
<%= form_with(model: ruby_mine, local: true) do |form| %>
  <% if ruby_mine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ruby_mine.errors.count, "error") %> prohibited this ruby_mine from being saved:</h2>

      <ul>
        <% ruby_mine.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ruby_mines/edit.html.erb
<h1>Editing Ruby Mine</h1>

<%= render 'form', ruby_mine: @ruby_mine %>

<%= link_to 'Show', @ruby_mine %> |
<%= link_to 'Back', ruby_mines_path %>

app/views/ruby_mines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ruby Mines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ruby_mines.each do |ruby_mine| %>
      <tr>
        <td><%= ruby_mine.name %></td>
        <td><%= ruby_mine.points %></td>
        <td><%= link_to 'Show', ruby_mine %></td>
        <td><%= link_to 'Edit', edit_ruby_mine_path(ruby_mine) %></td>
        <td><%= link_to 'Destroy', ruby_mine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ruby Mine', new_ruby_mine_path %>

app/views/ruby_mines/new.html.erb
<h1>New Ruby Mine</h1>

<%= render 'form', ruby_mine: @ruby_mine %>

<%= link_to 'Back', ruby_mines_path %>

app/views/ruby_mines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ruby_mine.name %>
</p>

<p>
  <strong>Points:</strong>
  <%= @ruby_mine.points %>
</p>

<%= link_to 'Edit', edit_ruby_mine_path(@ruby_mine) %> |
<%= link_to 'Back', ruby_mines_path %>

app/views/vs_codes/_form.html.erb
<%= form_with(model: vs_code, local: true) do |form| %>
  <% if vs_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vs_code.errors.count, "error") %> prohibited this vs_code from being saved:</h2>

      <ul>
        <% vs_code.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vs_codes/edit.html.erb
<h1>Editing Vs Code</h1>

<%= render 'form', vs_code: @vs_code %>

<%= link_to 'Show', @vs_code %> |
<%= link_to 'Back', vs_codes_path %>

app/views/vs_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vs Codes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vs_codes.each do |vs_code| %>
      <tr>
        <td><%= vs_code.name %></td>
        <td><%= vs_code.points %></td>
        <td><%= link_to 'Show', vs_code %></td>
        <td><%= link_to 'Edit', edit_vs_code_path(vs_code) %></td>
        <td><%= link_to 'Destroy', vs_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vs Code', new_vs_code_path %>

app/views/vs_codes/new.html.erb
<h1>New Vs Code</h1>

<%= render 'form', vs_code: @vs_code %>

<%= link_to 'Back', vs_codes_path %>

app/views/vs_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vs_code.name %>
</p>

<p>
  <strong>Points:</strong>
  <%= @vs_code.points %>
</p>

<%= link_to 'Edit', edit_vs_code_path(@vs_code) %> |
<%= link_to 'Back', vs_codes_path %>